services:
  mongo1:
    image: mongo:7
    container_name: mongo1
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    networks:
      - mongo-replica-net

  mongo2:
    image: mongo:7
    container_name: mongo2
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27018:27017"
    networks:
      - mongo-replica-net

  mongo3:
    image: mongo:7
    container_name: mongo3
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27019:27017"
    networks:
      - mongo-replica-net

networks:
  mongo-replica-net:
    driver: bridge